services:
  - type: web
    name: nss-backend
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
    autoDeploy: true
    
# Instructions for deployment:
# 1. Push this repository to GitHub
# 2. Connect to Render and import from GitHub
# 3. Set the following environment variables in Render Dashboard:
#    - SUPABASE_URL: Your Supabase project URL
#    - SUPABASE_SERVICE_ROLE_KEY: Your Supabase service role key  
#    - RAZORPAY_KEY_ID: Your Razorpay key ID
#    - RAZORPAY_KEY_SECRET: Your Razorpay key secret
# 4. Deploy the service
#
# Health check endpoint: /api/health
# Expected deployment URL: https://nss-backend.onrender.com
